/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.Sach.View;

import Main.GiamGia.Service.KhuyenMaiService;

import Main.Sach.Model.LichSuGia;
import Main.Sach.Model.NhaXuatBan;
import Main.Sach.Model.TacGia;
import Main.Sach.Model.TheLoai;
import Main.Sach.Model.SachModel;

import Main.Sach.Service.LichSuGiaService;

import Main.Sach.Service.SachService;
import Main.Sach.Service.ThuocTinhService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

import java.util.List;
import java.util.Objects;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class Sach extends javax.swing.JPanel {

    private KhuyenMaiService KMSV = new KhuyenMaiService();
    private SachService SSV = new SachService();
    private DefaultTableModel model = new DefaultTableModel();
    private int index = -1;
    private LichSuGiaService LSGSV = new LichSuGiaService();
    private ThuocTinhService TTSV = new ThuocTinhService();

    public Sach() {
        initComponents();
        fillTableSach(SSV.getAllSach());
        List<Main.Sach.Model.SachModel> sachList = TTSV.getTenSach();
        List<TheLoai> theLoaiList = TTSV.getTheLoai();
        List<TacGia> tacGiaList = TTSV.getTacGia();
        List<NhaXuatBan> nxbList = TTSV.getNXB();

        for (TheLoai theLoai : theLoaiList) {
            cbxTheLoai.addItem(theLoai.getMaTheLoai()); // Thêm mã thể loại vào combobox thay vì tên thể loại
        }

        for (TacGia tacGia : tacGiaList) {
            cbxTacGia.addItem(tacGia.getMaTacGia()); // Thêm mã tác giả vào combobox thay vì tên tác giả
        }

        for (NhaXuatBan nxb : nxbList) {
            cbxNXB.addItem(nxb.getMaNXB()); // Thêm mã nhà xuất bản vào combobox thay vì tên nhà xuất bản
        }
        fillCboMKM();
        cbx();

    }

    public void fillCboMKM() {
        cbxMKM.removeAllItems(); // Xóa tất cả các mục trong combobox trước khi thêm mới
        List<String> maKhuyenMaiList = SSV.getMaKhuyenMai(); // Lấy danh sách mã khuyến mãi từ service
        for (String maKhuyenMai : maKhuyenMaiList) {
            cbxMKM.addItem(maKhuyenMai); // Thêm mã khuyến mãi vào combobox
        }
    }

    private void cbx() {
        List<String> listMaSach = LSGSV.getAllMaSach();

        // Đưa danh sách mã sách vào combobox
        for (String maSach : listMaSach) {
            cbxChoiceMS.addItem(maSach);

            fillTableTheLoai(TTSV.getTheLoai());
            fillTableNXB(TTSV.getNXB());
            fillTableTacGia(TTSV.getTacGia());
        }
    }

    private void clearForm() {
        // Xóa dữ liệu trong các trường nhập liệu
        txtMaSach.setText("");
        txtNamXuatBan.setText("");
        txtSoLuong.setText("");
        txtDonGia.setText("");
        txtTenSach.setText("");

        cbxTheLoai.setSelectedIndex(-1);
        cbxTacGia.setSelectedIndex(-1);
        cbxNXB.setSelectedIndex(-1);
        cbxMKM.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pInput3 = new javax.swing.JPanel();
        lbMaSach3 = new javax.swing.JLabel();
        lbMaNXB3 = new javax.swing.JLabel();
        lbMaTL3 = new javax.swing.JLabel();
        lbMaTG3 = new javax.swing.JLabel();
        lbTenSach3 = new javax.swing.JLabel();
        lbSoLuong3 = new javax.swing.JLabel();
        lbDonGia3 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        lnNamXuatBan3 = new javax.swing.JLabel();
        txtNamXuatBan = new javax.swing.JTextField();
        txtMaSach = new javax.swing.JTextField();
        cbxNXB = new javax.swing.JComboBox<>();
        cbxTheLoai = new javax.swing.JComboBox<>();
        cbxTacGia = new javax.swing.JComboBox<>();
        txtTenSach = new javax.swing.JTextField();
        btnSuaSach = new javax.swing.JButton();
        btnXoaSach = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnThemSach = new javax.swing.JButton();
        btnXuatExcel = new javax.swing.JButton();
        cbxMKM = new javax.swing.JComboBox<>();
        btnApDung = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        txtTK = new javax.swing.JTextField();
        btnTKMS = new javax.swing.JButton();
        cbxTimKiem = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        txtTKDG_a = new javax.swing.JTextField();
        txtTKDG_b = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnTKDG = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenThuocTinh = new javax.swing.JTextField();
        RbtnNXB = new javax.swing.JRadioButton();
        RbtnTheLoai = new javax.swing.JRadioButton();
        RbtnTacGia = new javax.swing.JRadioButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        txtMaThuocTinh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblNXB = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblTheLoai = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblTacGia = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLSG = new javax.swing.JTable();
        cbxChoiceMS = new javax.swing.JComboBox<>();
        btnShow = new javax.swing.JButton();

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "QUẢN LÝ SÁCH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(255, 227, 227));

        pInput3.setBackground(new java.awt.Color(255, 255, 255));

        lbMaSach3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaSach3.setText("MÃ SÁCH:");

        lbMaNXB3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaNXB3.setText("NHÀ XUẤT BẢN");

        lbMaTL3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaTL3.setText("THỂ LOẠI");

        lbMaTG3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaTG3.setText("TÁC GIẢ");

        lbTenSach3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenSach3.setText("TÊN SÁCH:");

        lbSoLuong3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSoLuong3.setText("SỐ LƯỢNG:");

        lbDonGia3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDonGia3.setText("ĐƠN GIÁ:");

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDonGia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lnNamXuatBan3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnNamXuatBan3.setText("NĂM XUẤT BẢN:");

        txtNamXuatBan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachtxtMaSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pInput3Layout = new javax.swing.GroupLayout(pInput3);
        pInput3.setLayout(pInput3Layout);
        pInput3Layout.setHorizontalGroup(
            pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInput3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInput3Layout.createSequentialGroup()
                        .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDonGia3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSoLuong3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMaTG3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMaNXB3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMaTL3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMaSach3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMaSach)
                            .addComponent(cbxNXB, 0, 392, Short.MAX_VALUE)
                            .addComponent(cbxTheLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxTacGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pInput3Layout.createSequentialGroup()
                        .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lnNamXuatBan3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(lbTenSach3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamXuatBan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSoLuong)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(txtTenSach))))
                .addContainerGap())
        );
        pInput3Layout.setVerticalGroup(
            pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInput3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pInput3Layout.createSequentialGroup()
                        .addComponent(lbMaSach3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(pInput3Layout.createSequentialGroup()
                        .addComponent(txtMaSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaNXB3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaTL3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaTG3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenSach3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnNamXuatBan3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoLuong3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDonGia3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnSuaSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSuaSach.setText("SỬA");
        btnSuaSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSuaSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaSachMouseClicked(evt);
            }
        });
        btnSuaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSachActionPerformed(evt);
            }
        });

        btnXoaSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoaSach.setText("XÓA");
        btnXoaSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaSachMouseClicked(evt);
            }
        });
        btnXoaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSachActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLamMoi.setText("LÀM MỚI");
        btnLamMoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseClicked(evt);
            }
        });
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThemSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThemSach.setText("THÊM");
        btnThemSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnThemSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemSachMouseClicked(evt);
            }
        });
        btnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSachActionPerformed(evt);
            }
        });

        btnXuatExcel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXuatExcel.setText("XUẤT EXCEL");
        btnXuatExcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXuatExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatExcelMouseClicked(evt);
            }
        });
        btnXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelActionPerformed(evt);
            }
        });

        cbxMKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Khuyến Mãi" }));

        btnApDung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnApDung.setText("ÁP DỤNG");
        btnApDung.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnApDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApDungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pInput3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addComponent(btnThemSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSuaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(cbxMKM, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApDung, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))
                    .addComponent(btnXoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(pInput3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxMKM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(btnApDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(8, 8, 8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSuaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "TÌM KIẾM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        txtTK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTKMS.setBackground(new java.awt.Color(102, 255, 0));
        btnTKMS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTKMS.setForeground(new java.awt.Color(0, 51, 51));
        btnTKMS.setText("TÌM KIÉM");
        btnTKMS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTKMS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTKMSMouseClicked(evt);
            }
        });
        btnTKMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKMSActionPerformed(evt);
            }
        });

        cbxTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Sách", "Tên Sách", "Nhà Xuất Bản", "Thể Loại", "Tác Giả" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cbxTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnTKMS, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(644, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTKMS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Thuộc Tính", jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTKDG_a.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTKDG_b.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("NHẬP KHOẢNG KẾT THÚC");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("NHẬP KHOẢNG BẮT ĐẦU");

        btnTKDG.setBackground(new java.awt.Color(102, 255, 0));
        btnTKDG.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTKDG.setForeground(new java.awt.Color(0, 51, 51));
        btnTKDG.setText("TÌM KIÉM");
        btnTKDG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTKDG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTKDGMouseClicked(evt);
            }
        });
        btnTKDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKDGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTKDG_a, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(txtTKDG_b, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnTKDG, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTKDG_a, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTKDG_b, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTKDG, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jTabbedPane2.addTab("Đơn Giá", jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "THÔNG TIN CHI TIẾT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(204, 0, 51))); // NOI18N

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Nhà Xuất Bản", "Thể Loại", "Tác Giả", "Tên Sách", "Năm Xuất Bản", "Số Lượng", "Giá"
            }
        ));
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSach);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 596, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("THÔNG TIN CHI TIẾT", jPanel1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "THUỘC TÍNH SẢN PHẨM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel1.setText("Tên Thuộc Tính");

        buttonGroup1.add(RbtnNXB);
        RbtnNXB.setText("Nhà Xuất Bản");

        buttonGroup1.add(RbtnTheLoai);
        RbtnTheLoai.setText("Thể Loại");

        buttonGroup1.add(RbtnTacGia);
        RbtnTacGia.setText("Tác Giả");

        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã Thuộc Tính");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTenThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(236, 236, 236)
                .addComponent(RbtnNXB)
                .addGap(84, 84, 84)
                .addComponent(RbtnTheLoai)
                .addGap(110, 110, 110)
                .addComponent(RbtnTacGia)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RbtnNXB)
                        .addComponent(RbtnTheLoai)
                        .addComponent(RbtnTacGia))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "THÔNG TIN THUỘC TÍNH", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        tblNXB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã NXB", "Nhà Xuất Bản"
            }
        ));
        jScrollPane5.setViewportView(tblNXB);

        tblTheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Thể Loại", "Thể Loại"
            }
        ));
        jScrollPane6.setViewportView(tblTheLoai);

        tblTacGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Tác Giả", "Tác Giả"
            }
        ));
        jScrollPane7.setViewportView(tblTacGia);
        if (tblTacGia.getColumnModel().getColumnCount() > 0) {
            tblTacGia.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addGap(113, 113, 113)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1431, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 48, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("THUỘC TÍNH SẢN PHẨM", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblLSG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Sách", "Ngày Cập Nhật", "Giá Bán"
            }
        ));
        jScrollPane1.setViewportView(tblLSG);

        cbxChoiceMS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn" }));

        btnShow.setText("Hiện");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1322, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbxChoiceMS, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnShow)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxChoiceMS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LỊCH SỬ GIÁ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        hienThongTinLichSuGia();
    }//GEN-LAST:event_btnShowActionPerformed

    private void txtMaSachtxtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachtxtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachtxtMaSachActionPerformed

    private void btnSuaSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaSachMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaSachMouseClicked

    private void btnSuaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSachActionPerformed
        String maSach = txtMaSach.getText();
        String tenSach = txtTenSach.getText();

        String theLoai = cbxTheLoai.getSelectedItem().toString();
        String tacGia = cbxTacGia.getSelectedItem().toString();
        String nxb = cbxNXB.getSelectedItem().toString();
        String namXuatBan = txtNamXuatBan.getText();
        String soLuong = txtSoLuong.getText();
        String donGia = txtDonGia.getText();

        // Gọi phương thức từ service để sửa thông tin sách
        boolean suaThanhCong = TTSV.suaSach(maSach, tenSach, theLoai, tacGia, nxb, namXuatBan, soLuong, donGia);

        // Xử lý kết quả sửa sách
        if (suaThanhCong) {
            JOptionPane.showMessageDialog(this, "Sửa thông tin sách thành công!");
            fillTableSach(SSV.getAllSach());
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thông tin sách không thành công!");
            // Xử lý trường hợp sửa sách không thành công
        }
    }//GEN-LAST:event_btnSuaSachActionPerformed

    private void btnXoaSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaSachMouseClicked

    }//GEN-LAST:event_btnXoaSachMouseClicked

    private void btnXoaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSachActionPerformed
        // Lấy mã sách từ trường nhập liệu
        String maSach = txtMaSach.getText();

        // Gọi phương thức từ service để xóa sách
        boolean xoaThanhCong = TTSV.xoaSach(maSach);

        // Xử lý kết quả xóa sách
        if (xoaThanhCong) {
            JOptionPane.showMessageDialog(this, "Xóa sách thành công!");
            fillTableSach(SSV.getAllSach());
        } else {
            JOptionPane.showMessageDialog(this, "Xóa sách không thành công!");
            // Xử lý trường hợp xóa sách không thành công
        }
    }//GEN-LAST:event_btnXoaSachActionPerformed

    private void btnLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtMaSach.setText("");
        txtTenSach.setText("");
        cbxTheLoai.setSelectedIndex(1);
        cbxTacGia.setSelectedIndex(1);
        cbxNXB.setSelectedIndex(1);
        txtNamXuatBan.setText("");
        txtSoLuong.setText("");
        txtDonGia.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemSachMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemSachMouseClicked

    private void btnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSachActionPerformed
        String maSach = txtMaSach.getText();
        String tenSach = txtTenSach.getText();

        String theLoai = cbxTheLoai.getSelectedItem().toString();
        String tacGia = cbxTacGia.getSelectedItem().toString();
        String nxb = cbxNXB.getSelectedItem().toString();
        String namXuatBan = txtNamXuatBan.getText();
        String soLuong = txtSoLuong.getText();
        String donGia = txtDonGia.getText();

        boolean themThanhCong = TTSV.themSach(maSach, tenSach, theLoai, tacGia, nxb, namXuatBan, soLuong, donGia);

        // Xử lý kết quả thêm sách
        if (themThanhCong) {
            JOptionPane.showMessageDialog(this, "Thêm sách thành công!");
            fillTableSach(SSV.getAllSach());
            txtMaSach.setText("");

            txtNamXuatBan.setText("");
            txtSoLuong.setText("");
            txtDonGia.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm sách không thành công!");
            // Xử lý trường hợp thêm sách không thành công
        }
    }//GEN-LAST:event_btnThemSachActionPerformed

    private void btnXuatExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatExcelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatExcelMouseClicked

    private void btnXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelActionPerformed
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file to save");

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();

            if (!fileToSave.getAbsolutePath().endsWith(".xlsx")) {
                fileToSave = new File(fileToSave + ".xlsx");
            }

            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("SachData");

             model = (DefaultTableModel) tblSach.getModel();

            XSSFRow headerRow = sheet.createRow(0);
            for (int headings = 0; headings < model.getColumnCount(); headings++) { // Duyệt qua các cột
                headerRow.createCell(headings).setCellValue(model.getColumnName(headings));
            }

            for (int rows = 0; rows < model.getRowCount(); rows++) { // Duyệt qua các hàng
                XSSFRow row = sheet.createRow(rows + 1);
                for (int cols = 0; cols < model.getColumnCount(); cols++) { // Duyệt qua các cột
                    Object value = model.getValueAt(rows, cols);
                    if (value instanceof Boolean) {
                        row.createCell(cols).setCellValue((Boolean) value);
                    } else if (value instanceof Number) {
                        row.createCell(cols).setCellValue(((Number) value).doubleValue());
                    } else {
                        row.createCell(cols).setCellValue(Objects.toString(value, ""));
                    }
                }
            }

            try (FileOutputStream outputStream = new FileOutputStream(fileToSave)) {
                workbook.write(outputStream);
                JOptionPane.showMessageDialog(this, "Đã xuất file Excel thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(this, "File đang được mở ở chương trình khác!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Có lỗi khi ghi file!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXuatExcelActionPerformed

    private void btnTKMSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKMSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTKMSMouseClicked

    private void btnTKMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKMSActionPerformed

        // Lấy giá trị của combobox tìm kiếm và từ khóa tìm kiếm
        String timKiemTheo = cbxTimKiem.getSelectedItem().toString();
        String tuKhoa = txtTK.getText();
        // Xác định trường cần tìm kiếm trong cơ sở dữ liệu dựa trên giá trị của combobox
        String truongTimKiem = null;

        switch (timKiemTheo) {
            case "Mã Sách":
                truongTimKiem = "MaSach";
                break;
            case "Tên Sách":
                truongTimKiem = "TenSach";
                break;
            case "Nhà Xuất Bản":
                truongTimKiem = "MANXB";
                break;
            case "Thể Loại":
                truongTimKiem = "TheLoai";
                break;
            case "Tác Giả":
                truongTimKiem = "MATG";
                break;
            // Thêm các trường khác nếu cần
            default:
                // Xử lý khi không có lựa chọn nào được chọn
                break;
        }
        List<Main.Sach.Model.SachModel> ketQuaTimKiem = SSV.timKiemSach(truongTimKiem, tuKhoa);

        // Hiển thị kết quả tìm kiếm lên bảng
        hienThiDanhSachSachLenBang(ketQuaTimKiem);
        // Thực hiện tìm kiếm và hiển thị kết quả

    }//GEN-LAST:event_btnTKMSActionPerformed

    private void btnTKDGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKDGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTKDGMouseClicked

    private void btnTKDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKDGActionPerformed
        // Lấy giá trị của khoảng giá từ hai TextField

    }//GEN-LAST:event_btnTKDGActionPerformed

    private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
        int rowIndex = tblSach.getSelectedRow();

// Kiểm tra xem có hàng nào được click không
        if (rowIndex != -1) {
            // Lấy dữ liệu từ hàng được click
            String maSach = tblSach.getValueAt(rowIndex, 0) != null ? tblSach.getValueAt(rowIndex, 0).toString() : "";
            String tenSach = tblSach.getValueAt(rowIndex, 1) != null ? tblSach.getValueAt(rowIndex, 1).toString() : "";
            String theLoai = tblSach.getValueAt(rowIndex, 2) != null ? tblSach.getValueAt(rowIndex, 2).toString() : "";
            String tacGia = tblSach.getValueAt(rowIndex, 3) != null ? tblSach.getValueAt(rowIndex, 3).toString() : "";
            String nxb = tblSach.getValueAt(rowIndex, 4) != null ? tblSach.getValueAt(rowIndex, 4).toString() : "";
            String namXuatBan = tblSach.getValueAt(rowIndex, 5) != null ? tblSach.getValueAt(rowIndex, 5).toString() : "";
            String soLuong = tblSach.getValueAt(rowIndex, 6) != null ? tblSach.getValueAt(rowIndex, 6).toString() : "";
            String donGia = tblSach.getValueAt(rowIndex, 7) != null ? tblSach.getValueAt(rowIndex, 7).toString() : "";

            // Hiển thị dữ liệu lên các trường nhập liệu tương ứng
            txtMaSach.setText(maSach);
            txtTenSach.setText(tenSach);

            cbxTheLoai.setSelectedItem(theLoai);
            cbxTacGia.setSelectedItem(tacGia);
            cbxNXB.setSelectedItem(nxb);
            txtNamXuatBan.setText(namXuatBan);
            txtSoLuong.setText(soLuong);
            txtDonGia.setText(donGia);
        }


    }//GEN-LAST:event_tblSachMouseClicked

    private void btnApDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApDungActionPerformed
        // Lấy mã khuyến mãi từ combobox
        String maKhuyenMai = cbxMKM.getSelectedItem().toString();

        // Lấy chỉ số hàng được chọn trong bảng
        int rowIndex = tblSach.getSelectedRow();

        // Kiểm tra xem có hàng được chọn không
        if (rowIndex != -1) {
            // Lấy mã sách từ bảng
            String maSach = tblSach.getValueAt(rowIndex, 0).toString();

            // Áp dụng mã khuyến mãi cho sách
            boolean apDungThanhCong = SSV.apDungMaKhuyenMaiChoSach(maSach, maKhuyenMai);

            // Kiểm tra kết quả áp dụng mã khuyến mãi
            if (apDungThanhCong) {
                JOptionPane.showMessageDialog(this, "Áp dụng mã khuyến mãi thành công!");
                fillTableSach(SSV.getAllSach());
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Áp dụng mã khuyến mãi không thành công!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm trong bảng để áp dụng mã khuyến mãi!");
        }
    }//GEN-LAST:event_btnApDungActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (RbtnTheLoai.isSelected()) {
            // Xử lý khi RadioButton "Thể Loại" được chọn
            String maThuocTinh = txtMaThuocTinh.getText();
            String tenThuocTinh = txtTenThuocTinh.getText();

            // Gọi phương thức themThuocTinh() từ đối tượng TTSV (ThuocTinhService) với thông tin phù hợp
            boolean themThanhCong = TTSV.themTheLoai(maThuocTinh, tenThuocTinh);

            if (themThanhCong) {
                JOptionPane.showMessageDialog(this, "Thêm thông tin thể loại thành công!");
                fillTableTheLoai(TTSV.getTheLoai());
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thông tin thể loại không thành công!");
            }

            // Sau khi thêm, có thể thực hiện các công việc khác như đặt lại giá trị của các ô nhập liệu hoặc làm mới giao diện.
            // Ví dụ:
            txtMaThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu mã thể loại thành trống sau khi thêm
            txtTenThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu tên thể loại thành trống sau khi thêm
        } else if (RbtnTacGia.isSelected()) {
            // Xử lý khi RadioButton "Tác Giả" được chọn
            String maTacGia = txtMaThuocTinh.getText();
            String tenTacGia = txtTenThuocTinh.getText();

            // Gọi phương thức themTacGia() từ đối tượng TTSV (ThuocTinhService) với thông tin phù hợp
            boolean themThanhCong = TTSV.themTacGia(maTacGia, tenTacGia);

            if (themThanhCong) {
                JOptionPane.showMessageDialog(this, "Thêm thông tin tác giả thành công!");
                fillTableTacGia(TTSV.getTacGia());
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thông tin tác giả không thành công!");
            }

            // Sau khi thêm, có thể thực hiện các công việc khác như đặt lại giá trị của các ô nhập liệu hoặc làm mới giao diện.
            // Ví dụ:
            txtMaThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu mã tác giả thành trống sau khi thêm
            txtTenThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu tên tác giả thành trống sau khi thêm
        } else if (RbtnNXB.isSelected()) {
            // Xử lý khi RadioButton "Nhà Xuất Bản" được chọn
            String maNXB = txtMaThuocTinh.getText();
            String tenNXB = txtTenThuocTinh.getText();

            // Gọi phương thức themNhaXuatBan() từ đối tượng TTSV (ThuocTinhService) với thông tin phù hợp
            boolean themThanhCong = TTSV.themNhaXuatBan(maNXB, tenNXB);

            if (themThanhCong) {
                JOptionPane.showMessageDialog(this, "Thêm thông tin nhà xuất bản thành công!");
                fillTableNXB(TTSV.getNXB());
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thông tin nhà xuất bản không thành công!");
            }

            // Sau khi thêm, có thể thực hiện các công việc khác như đặt lại giá trị của các ô nhập liệu hoặc làm mới giao diện.
            // Ví dụ:
            txtMaThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu mã nhà xuất bản thành trống sau khi thêm
            txtTenThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu tên nhà xuất bản thành trống sau khi thêm
        } else {
            // Nếu không có RadioButton nào được chọn, hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(this, "Vui lòng chọn loại thông tin trước khi thêm!");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (RbtnTheLoai.isSelected()) {
            // Xử lý khi RadioButton "Thể Loại" được chọn
            String maTheLoai = txtMaThuocTinh.getText();
            String tenTheLoai = txtTenThuocTinh.getText();

            // Gọi phương thức suaTheLoai() từ đối tượng TTSV (ThuocTinhService) với thông tin phù hợp
            boolean suaThanhCong = TTSV.suaTheLoai(maTheLoai, tenTheLoai);

            if (suaThanhCong) {
                JOptionPane.showMessageDialog(this, "Sửa thông tin thể loại thành công!");
                fillTableTheLoai(TTSV.getTheLoai());
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thông tin thể loại không thành công!");
            }

            // Sau khi sửa, có thể thực hiện các công việc khác như đặt lại giá trị của các ô nhập liệu hoặc làm mới giao diện.
            // Ví dụ:
            txtMaThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu mã thể loại thành trống sau khi sửa
            txtTenThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu tên thể loại thành trống sau khi sửa
        } else if (RbtnTacGia.isSelected()) {
            // Xử lý khi RadioButton "Tác Giả" được chọn
            String maTacGia = txtMaThuocTinh.getText();
            String tenTacGia = txtTenThuocTinh.getText();

            // Gọi phương thức suaTacGia() từ đối tượng TTSV (ThuocTinhService) với thông tin phù hợp
            boolean suaThanhCong = TTSV.suaTacGia(maTacGia, tenTacGia);

            if (suaThanhCong) {
                JOptionPane.showMessageDialog(this, "Sửa thông tin tác giả thành công!");
                fillTableTacGia(TTSV.getTacGia());
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thông tin tác giả không thành công!");
            }

            // Sau khi sửa, có thể thực hiện các công việc khác như đặt lại giá trị của các ô nhập liệu hoặc làm mới giao diện.
            // Ví dụ:
            txtMaThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu mã tác giả thành trống sau khi sửa
            txtTenThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu tên tác giả thành trống sau khi sửa
        } else if (RbtnNXB.isSelected()) {
            // Xử lý khi RadioButton "Nhà Xuất Bản" được chọn
            String maNXB = txtMaThuocTinh.getText();
            String tenNXB = txtTenThuocTinh.getText();

            // Gọi phương thức suaNhaXuatBan() từ đối tượng TTSV (ThuocTinhService) với thông tin phù hợp
            boolean suaThanhCong = TTSV.suaNhaXuatBan(maNXB, tenNXB);

            if (suaThanhCong) {
                JOptionPane.showMessageDialog(this, "Sửa thông tin nhà xuất bản thành công!");
                fillTableNXB(TTSV.getNXB());
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thông tin nhà xuất bản không thành công!");
            }

            // Sau khi sửa, có thể thực hiện các công việc khác như đặt lại giá trị của các ô nhập liệu hoặc làm mới giao diện.
            // Ví dụ:
            txtMaThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu mã nhà xuất bản thành trống sau khi sửa
            txtTenThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu tên nhà xuất bản thành trống sau khi sửa
        } else {
            // Nếu không có RadioButton nào được chọn, hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(this, "Vui lòng chọn loại thông tin trước khi sửa!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (RbtnTheLoai.isSelected()) {
            // Xử lý khi RadioButton "Thể Loại" được chọn
            String maTheLoai = txtMaThuocTinh.getText();

            // Gọi phương thức xoaTheLoai() từ đối tượng TTSV (ThuocTinhService) với mã thể loại phù hợp
            boolean xoaThanhCong = TTSV.xoaTheLoai(maTheLoai);

            if (xoaThanhCong) {
                JOptionPane.showMessageDialog(this, "Xóa thông tin thể loại thành công!");
                fillTableTheLoai(TTSV.getTheLoai());
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thông tin thể loại không thành công!");
            }

            // Sau khi xóa, có thể thực hiện các công việc khác như đặt lại giá trị của các ô nhập liệu hoặc làm mới giao diện.
            // Ví dụ:
            txtMaThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu mã thể loại thành trống sau khi xóa
            txtTenThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu tên thể loại thành trống sau khi xóa
        } else if (RbtnTacGia.isSelected()) {
            // Xử lý khi RadioButton "Tác Giả" được chọn
            String maTacGia = txtMaThuocTinh.getText();

            // Gọi phương thức xoaTacGia() từ đối tượng TTSV (ThuocTinhService) với mã tác giả phù hợp
            boolean xoaThanhCong = TTSV.xoaTacGia(maTacGia);

            if (xoaThanhCong) {
                JOptionPane.showMessageDialog(this, "Xóa thông tin tác giả thành công!");
                fillTableTacGia(TTSV.getTacGia());
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thông tin tác giả không thành công!");
            }

            // Sau khi xóa, có thể thực hiện các công việc khác như đặt lại giá trị của các ô nhập liệu hoặc làm mới giao diện.
            // Ví dụ:
            txtMaThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu mã tác giả thành trống sau khi xóa
            txtTenThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu tên tác giả thành trống sau khi xóa
        } else if (RbtnNXB.isSelected()) {
            // Xử lý khi RadioButton "Nhà Xuất Bản" được chọn
            String maNXB = txtMaThuocTinh.getText();

            // Gọi phương thức xoaNhaXuatBan() từ đối tượng TTSV (ThuocTinhService) với mã nhà xuất bản phù hợp
            boolean xoaThanhCong = TTSV.xoaNhaXuatBan(maNXB);

            if (xoaThanhCong) {
                JOptionPane.showMessageDialog(this, "Xóa thông tin nhà xuất bản thành công!");
                fillTableNXB(TTSV.getNXB());
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thông tin nhà xuất bản không thành công!");
            }

            // Sau khi xóa, có thể thực hiện các công việc khác như đặt lại giá trị của các ô nhập liệu hoặc làm mới giao diện.
            // Ví dụ:
            txtMaThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu mã nhà xuất bản thành trống sau khi xóa
            txtTenThuocTinh.setText(""); // Đặt lại giá trị của ô nhập liệu tên nhà xuất bản thành trống sau khi xóa
        } else {
            // Nếu không có RadioButton nào được chọn, hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(this, "Vui lòng chọn loại thông tin trước khi xóa!");
        }
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtnNXB;
    private javax.swing.JRadioButton RbtnTacGia;
    private javax.swing.JRadioButton RbtnTheLoai;
    private javax.swing.JButton btnApDung;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaSach;
    private javax.swing.JButton btnTKDG;
    private javax.swing.JButton btnTKMS;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemSach;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaSach;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cbxChoiceMS;
    private javax.swing.JComboBox<String> cbxMKM;
    private javax.swing.JComboBox<String> cbxNXB;
    private javax.swing.JComboBox<String> cbxTacGia;
    private javax.swing.JComboBox<String> cbxTheLoai;
    private javax.swing.JComboBox<String> cbxTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbDonGia3;
    private javax.swing.JLabel lbMaNXB3;
    private javax.swing.JLabel lbMaSach3;
    private javax.swing.JLabel lbMaTG3;
    private javax.swing.JLabel lbMaTL3;
    private javax.swing.JLabel lbSoLuong3;
    private javax.swing.JLabel lbTenSach3;
    private javax.swing.JLabel lnNamXuatBan3;
    private javax.swing.JPanel pInput3;
    private javax.swing.JTable tblLSG;
    private javax.swing.JTable tblNXB;
    private javax.swing.JTable tblSach;
    private javax.swing.JTable tblTacGia;
    private javax.swing.JTable tblTheLoai;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtMaThuocTinh;
    private javax.swing.JTextField txtNamXuatBan;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txtTKDG_a;
    private javax.swing.JTextField txtTKDG_b;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTenThuocTinh;
    // End of variables declaration//GEN-END:variables

    private void hienThongTinLichSuGia() {
        String maSach = (String) cbxChoiceMS.getSelectedItem();
        List<LichSuGia> lichSuGiaList = LSGSV.getLichSuGiaByMaSach(maSach);

        // Xóa dữ liệu cũ trên bảng
        DefaultTableModel model = (DefaultTableModel) tblLSG.getModel();
        model.setRowCount(0);

        // Thêm dữ liệu mới từ danh sách lịch sử giá
        for (LichSuGia lichSuGia : lichSuGiaList) {
            model.addRow(new Object[]{lichSuGia.getMaSach(), lichSuGia.getNgayCapNhat(), lichSuGia.getGiaBan()});
        }

    }

    private void fillTableTheLoai(List<TheLoai> theLoai) {

        model = (DefaultTableModel) tblTheLoai.getModel();
        model.setRowCount(0);
        for (TheLoai tl : theLoai) {
            model.addRow(tl.toDataRow());
        }
    }

    private void fillTableNXB(List<NhaXuatBan> nxb) {

        model = (DefaultTableModel) tblNXB.getModel();
        model.setRowCount(0);

        for (NhaXuatBan n : nxb) {
            model.addRow(n.toDataRow());
        }

    }

    private void fillTableTacGia(List<TacGia> tacGia) {

        model = (DefaultTableModel) tblTacGia.getModel();
        model.setRowCount(0);

        for (TacGia tg : tacGia) {
            model.setRowCount(0);

            model.addRow(tg.toDataRow());
        }

    }

    private void fillTableSach(List<Main.Sach.Model.SachModel> allSach) {
        model = (DefaultTableModel) tblSach.getModel();
        model.setRowCount(0);
        for (Main.Sach.Model.SachModel sach : allSach) {
            model.addRow(sach.toDataRow());
        }
    }

    private void hienThiDanhSachSachLenBang(List<SachModel> ketQuaTimKiem) {
        DefaultTableModel model = (DefaultTableModel) tblSach.getModel();
        model.setRowCount(0); // Xóa tất cả các hàng trong bảng

        for (SachModel sach : ketQuaTimKiem) {
            Object[] row = {
                sach.getMaSach(),
                sach.getNhaXuatBan(),
                sach.getTheLoai(),
                sach.getTacGia(),
                sach.getTenSach(),
                sach.getNamXuatBan(),
                sach.getSoLuong(),
                sach.getGiaMua()
            // Thêm các cột khác nếu cần
            };
            model.addRow(row); // Thêm một hàng mới vào bảng với dữ liệu của sách
        }
    }

}
