CREATE DATABASE DA1;


CREATE TABLE KHACHHANG (
    MAKH NVARCHAR(50) PRIMARY KEY,
    TENKH NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(50),
    EMAIL NVARCHAR(50),
    SDT NVARCHAR(20),
    NgaySinh DATE
);



CREATE TABLE NHANVIEN (
    IDNV NVARCHAR(50) PRIMARY KEY,
    TEN NVARCHAR(50) NOT NULL,
    GIOITINH NVARCHAR(50),
    NGAYSINH DATE,
    EMAIL NVARCHAR(50),
    SDT NVARCHAR(50),
    TAIKHOAN NVARCHAR(50) NOT NULL,
    PASWORD CHAR(20) NOT NULL
);


CREATE TABLE NHACUNGCAP (
    MANCC NVARCHAR(50) PRIMARY KEY,
    TENNHACUNGCAP NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(50),
    EMAIL NVARCHAR(50),
    SDT NVARCHAR(20),
    NGAYNHAP DATE,
    MOTA NVARCHAR(255)
);



CREATE TABLE THELOAI(
    MATL NVARCHAR(50) PRIMARY KEY,
    THELOAI NVARCHAR(50) NOT NULL
);

CREATE TABLE TACGIA(
    MATG NVARCHAR(50) PRIMARY KEY,
    TENTG NVARCHAR(50),
    DIACHI NVARCHAR(50),
    SDT NVARCHAR(50)
);


CREATE TABLE NHAXUATBAN (
    MANXB NVARCHAR(50) PRIMARY KEY,
    TENNXB NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(50),
    EMAIL NVARCHAR(50),
    SDT NVARCHAR(20)
);

CREATE TABLE SACH(
    MASACH NVARCHAR(50) PRIMARY KEY,
    MANXB NVARCHAR(50),
    THELOAI NVARCHAR(50) NOT NULL,
    MATG NVARCHAR(50),
    TENSACH NVARCHAR(50),
    NAMXUATBAN INT,
    SOLUONG INT,
    GIAMUA INT,
    ANH NVARCHAR(50),
    FOREIGN KEY(THELOAI) REFERENCES THELOAI(MATL),
    FOREIGN KEY(MANXB) REFERENCES NHAXUATBAN(MANXB),
	 FOREIGN KEY(MATG) REFERENCES TACGIA(MATG)
);


CREATE TABLE SACH_NHACUNGCAP (
    MASACH NVARCHAR(50) NOT NULL,
    MANCC NVARCHAR(50) NOT NULL,
    PRIMARY KEY (MASACH, MANCC),
    FOREIGN KEY (MASACH) REFERENCES SACH(MASACH),
    FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);

ả
CREATE TABLE SACH_TACGIA (
    MASACH NVARCHAR(50) NOT NULL,
    MATG NVARCHAR(50) NOT NULL,
    PRIMARY KEY (MASACH, MATG),
    FOREIGN KEY (MASACH) REFERENCES SACH(MASACH),
    FOREIGN KEY (MATG) REFERENCES TACGIA(MATG)
);

CREATE TABLE KHUYENMAI (
    MAKM NVARCHAR(50) PRIMARY KEY,
    TENKHUYENMAI NVARCHAR(50) NOT NULL,
    
    NGAYBATDAU DATETIME,
    NGAYKETTHUC DATETIME,
	GIAMGIA INT,
    TRANGTHAI NVARCHAR(50) NOT NULL,
	 
);

CREATE TABLE CTKHUYENMAI (
    MAKM NVARCHAR(50) NOT NULL,
    MASACH NVARCHAR(50) NOT NULL,
   
    FOREIGN KEY(MAkm) REFERENCES KHUYENMAI(MAKM),
    FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
    PRIMARY KEY (MAkm, MASACH)
);


CREATE TABLE HOADON (
    MAHD NVARCHAR(50) PRIMARY KEY,
    MAKH NVARCHAR(50) NOT NULL,
    IDNV NVARCHAR(50) NOT NULL,
    NGAYLAP DATETIME,
    TONGTIEN INT,
    GIAMGIA INT NOT NULL,
    THANHTIEN INT,
    FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY(IDNV) REFERENCES NHANVIEN(IDNV)
);



CREATE TABLE HOADONCT (
    MAHD NVARCHAR(50) NOT NULL,
    MASACH NVARCHAR(50) NOT NULL,
    SOLUONG NVARCHAR(50) NOT NULL,
    GIAMUA INT NOT NULL,
    THANHTIEN INT NOT NULL,
    PRIMARY KEY (MAHD, MASACH),
    FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
    FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD)
);



CREATE TABLE PHIEUNHAP (
    MAPN NVARCHAR(50) PRIMARY KEY,
    MANV NVARCHAR(50) NOT NULL,
    MANCC NVARCHAR(50) NOT NULL,
    NGAYNHAP DATETIME,
    TONGTIEN INT,
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(IDNV),
    FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);

CREATE TABLE CTPHIEUNHAP (
    MACTPN NVARCHAR(50) NOT NULL,
    MAPN NVARCHAR(50) NOT NULL,
    MASACH NVARCHAR(50) NOT NULL,
    SOLUONG INT,
    DONGIA INT,
    THANHTIEN INT,
    FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN),
    FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
);


CREATE TABLE LICHSUGIA (
    MASACH NVARCHAR(50),
    NGAYCAPNHAT DATE NOT NULL,
    GIABAN INT,
    FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
    PRIMARY KEY (MASACH, NGAYCAPNHAT) -- Đặt cặp này làm PRIMARY KEY
);

CREATE TABLE VOUCHER (
    MAVOUCHER NVARCHAR(50) PRIMARY KEY,
    MAHD NVARCHAR(50) NOT NULL,
    TENVOUCHER NVARCHAR(50) NOT NULL,
    GIAMGIA INT,
    FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD)
);