


CREATE TABLE KHACHHANG (
    MAKH NVARCHAR(50) PRIMARY KEY,
    TENKH NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(50),
    EMAIL NVARCHAR(50),
    SDT NVARCHAR(20),
    NgaySinh DATE
);




CREATE TABLE NHANVIEN (
    IDNV NVARCHAR(50) PRIMARY KEY,
    TEN NVARCHAR(50) NOT NULL,
    GIOITINH NVARCHAR(50),
    NGAYSINH DATE,
    EMAIL NVARCHAR(50),
    SDT NVARCHAR(50),
    TAIKHOAN NVARCHAR(50) NOT NULL,
    MATKHAU CHAR(20) NOT NULL,
	CHUCVU nvarchar(50)
);
select * from nhanvien

CREATE TABLE NHACUNGCAP (
    MANCC NVARCHAR(50) PRIMARY KEY,
    TENNHACUNGCAP NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(50),
    EMAIL NVARCHAR(50),
    SDT NVARCHAR(20),
    
    MOTA NVARCHAR(255)
);



CREATE TABLE THELOAI(
    MATL NVARCHAR(50) PRIMARY KEY,
    THELOAI NVARCHAR(50) NOT NULL
);

CREATE TABLE TACGIA(
    MATG NVARCHAR(50) PRIMARY KEY,
    TENTG NVARCHAR(50),
    DIACHI NVARCHAR(50),
    SDT NVARCHAR(50)
);


CREATE TABLE NHAXUATBAN (
    MANXB NVARCHAR(50) PRIMARY KEY,
    TENNXB NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(50),
    EMAIL NVARCHAR(50),
    SDT NVARCHAR(20)
);

CREATE TABLE SACH(
    MASACH NVARCHAR(50) PRIMARY KEY,
    MANXB NVARCHAR(50),
    THELOAI NVARCHAR(50) NOT NULL,
    MATG NVARCHAR(50),
    TENSACH NVARCHAR(50),
    NAMXUATBAN INT,
    SOLUONG INT,
    GIAMUA INT,
    ANH NVARCHAR(50),
    FOREIGN KEY(THELOAI) REFERENCES THELOAI(MATL),
    FOREIGN KEY(MANXB) REFERENCES NHAXUATBAN(MANXB),
	 FOREIGN KEY(MATG) REFERENCES TACGIA(MATG)
);


CREATE TABLE SACH_NHACUNGCAP (
    MASACH NVARCHAR(50) NOT NULL,
    MANCC NVARCHAR(50) NOT NULL,
    PRIMARY KEY (MASACH, MANCC),
    FOREIGN KEY (MASACH) REFERENCES SACH(MASACH),
    FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);


CREATE TABLE SACH_TACGIA (
    MASACH NVARCHAR(50) NOT NULL,
    MATG NVARCHAR(50) NOT NULL,
    PRIMARY KEY (MASACH, MATG),
    FOREIGN KEY (MASACH) REFERENCES SACH(MASACH),
    FOREIGN KEY (MATG) REFERENCES TACGIA(MATG)
);

CREATE TABLE KHUYENMAI (
    MAKM NVARCHAR(50) PRIMARY KEY,
    TENKHUYENMAI NVARCHAR(50) NOT NULL,
    
    NGAYBATDAU DATE,
    NGAYKETTHUC DATE,
	GIAMGIA INT,
    TRANGTHAI NVARCHAR(50) NOT NULL,
	 
);

CREATE TABLE CTKHUYENMAI (
    MAKM NVARCHAR(50) NOT NULL,
    MASACH NVARCHAR(50) NOT NULL,
   
    FOREIGN KEY(MAkm) REFERENCES KHUYENMAI(MAKM),
    FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
    PRIMARY KEY (MAkm, MASACH)
);



CREATE TABLE HOADON (
    MAHD NVARCHAR(50) PRIMARY KEY,
    MAKH NVARCHAR(50) NOT NULL,
    IDNV NVARCHAR(50) NOT NULL,
	MASACH  NVARCHAR(50) NOT NULL,
	SOLUONG int null,
    NGAYLAP DATETIME,
    TONGTIEN INT,

    THANHTIEN INT,
	FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
    FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY(IDNV) REFERENCES NHANVIEN(IDNV)
);
select * from hoadon


CREATE TABLE HOADONCT (
	MACTHD NVARCHAR(50)  NOT NULL,
    MAHD NVARCHAR(50) NOT NULL,
    MASACH NVARCHAR(50) NOT NULL,
    SOLUONG NVARCHAR(50) NOT NULL,
    GIAMUA INT NOT NULL,

    THANHTIEN INT NOT NULL,
    PRIMARY KEY (MACTHD,MAHD),
    FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
    FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD)
);


CREATE TABLE PHIEUNHAP (
    MAPN NVARCHAR(50) PRIMARY KEY,
    MANV NVARCHAR(50) NOT NULL,
    MANCC NVARCHAR(50) NOT NULL,
	SOLUONG INT,
	DONGIA int,
    NGAYNHAP DATETIME NOT NULL,
    TONGTIEN = soluong * dongia,
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(IDNV),
    FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);



CREATE TABLE CTPHIEUNHAP (
    MAPN NVARCHAR(50),
	MANV NVARCHAR(50) NOT NULL,
    MASACH NVARCHAR(50),
    MANCC NVARCHAR(50),
    SOLUONG INT,
    DONGIA INT,
    NGAYNHAP DATETIME,
   
    PRIMARY KEY (MAPN, MASACH),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(IDNV),
    FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN),
    FOREIGN KEY (MASACH) REFERENCES SACH(MASACH),
    FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);
ALTER TABLE PHIEUNHAP
add TONGTIEN as soluong * dongia


select * from ctphieunhap




CREATE TABLE LICHSUGIA (
    MASACH NVARCHAR(50),
    NGAYCAPNHAT DATETIME NOT NULL,
    GIABAN INT,
    FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
    PRIMARY KEY (MASACH, NGAYCAPNHAT) -- Đặt cặp này làm PRIMARY KEY
);
select * from lichsugia
CREATE TABLE VOUCHER (
    MAVOUCHER NVARCHAR(50) PRIMARY KEY,
	dieukien int,
    TENVOUCHER NVARCHAR(50) NOT NULL,
    GIAMGIA INT
	
    
);
drop table voucher
CREATE TABLE CTVOUCHER (
    MAVOUCHER NVARCHAR(50),
    MAHD NVARCHAR(50),
    CONSTRAINT PK_CTVOUCHER PRIMARY KEY (MAVOUCHER, MAHD),
    FOREIGN KEY (MAVOUCHER) REFERENCES VOUCHER(MAVOUCHER),
    FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
);


CREATE or alter PROCEDURE DoiMatKhau 
    @p_taiKhoan NVARCHAR(255),
    @p_matKhauMoi NVARCHAR(255)
AS
BEGIN
    UPDATE NHANVIEN
    SET MATKHAU = @p_matKhauMoi
    WHERE TAIKHOAN = @p_taiKhoan;
END



INSERT INTO KHACHHANG (MAKH, TENKH, DIACHI, EMAIL, SDT, NgaySinh)
VALUES ('KH001', N'Tên khách hàng', N'Địa chỉ khách hàng', N'emailkh@example.com', N'0999999999', '2000-01-01');
------------
INSERT INTO NHANVIEN (IDNV, TEN, GIOITINH, NGAYSINH, EMAIL, SDT, TAIKHOAN, MATKHAU, CHUCVU)
VALUES ('NV001', N'Tên nhân viên', N'Nam', '2000-01-01', N'emailnv@example.com', N'0999999999', 'taikhoan1', 'matkhau1', N'Nhân viên');
INSERT INTO NHANVIEN (IDNV, TEN, GIOITINH, NGAYSINH, EMAIL, SDT, TAIKHOAN, MATKHAU, CHUCVU)
VALUES ('NV002', N'Tên nhân viên', N'Nữ', '2000-01-01', N'huyvtm580@gmail.com', N'0999999999', 'taikhoan2', 'matkhau2', N'Nhân viên');
INSERT INTO NHANVIEN (IDNV, TEN, GIOITINH, NGAYSINH, EMAIL, SDT, TAIKHOAN, MATKHAU, CHUCVU)
VALUES ('NV004', N'Đặng Hồng Huy', N'Nam', '2004-09-28', N'huyvtm580@gmail.com', N'0987783723', 'huydhph45901', '88888888', N'Nhân viên');


select * from sach
-----------
INSERT INTO NHACUNGCAP (MANCC, TENNHACUNGCAP, DIACHI, EMAIL, SDT, MOTA)
VALUES ('NCC001', N'Tên nhà cung cấp', N'Địa chỉ nhà cung cấp', N'emailncc@example.com', N'0999999999', N'Mô tả về nhà cung cấp');
----------
INSERT INTO THELOAI (MATL, THELOAI)
VALUES ('TL001', N'Tên thể loại sách');
--------
INSERT INTO TACGIA (MATG, TENTG, DIACHI, SDT)
VALUES ('TG001', N'Tên tác giả', N'Địa chỉ tác giả', N'0999999999');
--------
INSERT INTO NHAXUATBAN (MANXB, TENNXB, DIACHI, EMAIL, SDT)
VALUES ('NXB001', N'Tên nhà xuất bản', N'Địa chỉ nhà xuất bản', N'emailnxb@example.com', N'0999999999');
---
INSERT INTO SACH (MASACH, MANXB, THELOAI, MATG, TENSACH, NAMXUATBAN, SOLUONG, GIAMUA, ANH)
VALUES ('S001', 'NXB001', 'TL001', 'TG001', N'Tên sách', 2024, 100, 50000, N'link_anh_sach.jpg');
-----------
INSERT INTO SACH_NHACUNGCAP (MASACH, MANCC)
VALUES ('S001', 'NCC001');
---------
INSERT INTO SACH_TACGIA (MASACH, MATG)
VALUES ('S001', 'TG001');
----------------





-------------
INSERT INTO CTKHUYENMAI (MAKM, MASACH)
VALUES ('KM001', 'S001');




-----------
INSERT INTO HOADON (MAHD, MAKH, IDNV, MASACH, SOLUONG, NGAYLAP, TONGTIEN, THANHTIEN)
VALUES ('HD001', 'KH001', 'NV001', 'S001', 2, '2024-04-12 08:00:00', 100000, 100000);
select * from hoadon
-------------
INSERT INTO HOADONCT (MACTHD, MAHD, MASACH, SOLUONG, GIAMUA, THANHTIEN)
VALUES ('HDCT001', 'HD001', 'S001', 2, 50000, 100000);
------------
INSERT INTO PHIEUNHAP (MAPN, MANV, MANCC,SOLUONG,NGAYNHAP, TONGTIEN) 
VALUES ('PN001', 'NV001', 'NCC001',100, '2024-04-13 10:00:00', 5000000);

select * from phieunhap

------------
INSERT INTO CTPHIEUNHAP (MAPN, MANV, MASACH, MANCC, SOLUONG, DONGIA, NGAYNHAP) 
VALUES ('PN001', 'NV001', 'S001', 'NCC001', 100, 50000, '2024-04-13 10:00:00');

DECLARE @TONGTIEN_CTPN INT;
SET @TONGTIEN_CTPN = (SELECT SOLUONG * DONGIA FROM CTPHIEUNHAP WHERE MAPN = 'PN001');

select * from voucher
-------------------
INSERT INTO LICHSUGIA (MASACH, NGAYCAPNHAT, GIABAN)
VALUES ('S001', '2024-04-12', 60000);
---------
INSERT INTO VOUCHER (MAVOUCHER, MAHD, TENVOUCHER, GIAMGIA, NGAYKETTHUC)
VALUES ('VC001', 'HD001', N'Tên voucher', 5000, '2024-04-30');
---------
INSERT INTO CTVOUCHER (MAVOUCHER, MAHD)
VALUES ('VC001', 'HD001');

-- Truy vấn bảng KHACHHANG
SELECT * FROM KHACHHANG;

-- Truy vấn bảng NHANVIEN
SELECT * FROM NHANVIEN;

-- Truy vấn bảng NHACUNGCAP
SELECT * FROM NHACUNGCAP;

-- Truy vấn bảng THELOAI
SELECT * FROM THELOAI;

-- Truy vấn bảng TACGIA
SELECT * FROM TACGIA;

-- Truy vấn bảng NHAXUATBAN
SELECT * FROM NHAXUATBAN;

-- Truy vấn bảng SACH
SELECT * FROM SACH;

-- Truy vấn bảng SACH_NHACUNGCAP
SELECT * FROM SACH_NHACUNGCAP;

-- Truy vấn bảng SACH_TACGIA
SELECT * FROM SACH_TACGIA;

-- Truy vấn bảng KHUYENMAI
SELECT * FROM KHUYENMAI;

-- Truy vấn bảng CTKHUYENMAI
SELECT * FROM CTKHUYENMAI;

-- Truy vấn bảng HOADON
SELECT * FROM HOADON;

-- Truy vấn bảng HOADONCT
SELECT * FROM HOADONCT;

-- Truy vấn bảng PHIEUNHAP
SELECT * FROM PHIEUNHAP;

-- Truy vấn bảng CTPHIEUNHAP
SELECT * FROM CTPHIEUNHAP;

-- Truy vấn bảng LICHSUGIA
SELECT * FROM LICHSUGIA;

-- Truy vấn bảng VOUCHER
SELECT * FROM VOUCHER;

-- Truy vấn bảng CTVOUCHER
SELECT * FROM CTVOUCHER;
UPDATE hoadon SET IDNV = 'HAHHAHAH' WHERE MaHD = '6A395B6D-6B4A-4B39-AF7D-91D928C793AE'
select * from hoadon