/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import DAO.SachDAO;
import DTO.SachDTO;
import java.awt.Image;
import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.util.UUID;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author admin
 */
public class FromQlySach extends javax.swing.JFrame {

    private SachDAO qs = new SachDAO();
    private DefaultTableModel model = new DefaultTableModel();
    private int index = -1;
    private BufferedImage i = null;//Hình ảnh chọn từ file
    private String imgName = "null";

    /**
     * Creates new form QlySach
     */
    public FromQlySach() {
        initComponents();
        setLocationRelativeTo(null);
        cboMaNxb.removeAllItems();
        cboMaNxb.addItem("NXB1");
        cboMaNxb.addItem("NXB2");
        cboMaNxb.addItem("NXB3");
        cboMaNxb.addItem("NXB4");
        cboMaNxb.addItem("NXB5");
        cboMaTl.removeAllItems();
        cboMaTl.addItem("TL1");
        cboMaTl.addItem("TL2");
        cboMaTl.addItem("TL3");
        cboMaTl.addItem("TL4");
        cboMaTl.addItem("TL5");
        cboMaTl.addItem("TL6");
        cboMaTl.addItem("TL7");
        cboMaTl.addItem("TL8");
        cboMaTl.addItem("TL9");
        cboMaTl.addItem("TL10");
        cboMaTg.removeAllItems();
        cboMaTg.addItem("TG1");
        cboMaTg.addItem("TG2");
        cboMaTg.addItem("TG3");
        cboMaTg.addItem("TG4");
        cboMaTg.addItem("TG5");
        this.fillTable(qs.selectAll());
    }

    void fillTable(List<SachDTO> list) {
        model = (DefaultTableModel) tblBang.getModel();
        model.setRowCount(0);
        for (SachDTO ql : list) {
            model.addRow(ql.toDataRow());
        }
    }

    void showData(int index) {
        int i = tblBang.getSelectedRow();
        if (i >= 0) {
            if (tblBang.getRowSorter() != null) {
                i = tblBang.getRowSorter().convertRowIndexToModel(i);
            }
            imgName = tblBang.getModel().getValueAt(i, 8).toString();
            Image newImage;
            try {
                newImage = new ImageIcon("./src/img/SanPham/" + imgName).getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT);
            } catch (NullPointerException E) {
                newImage = new ImageIcon("./src/img/SanPham/NoImage.jpg").getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT);
            }
            txtMaSach.setText(tblBang.getValueAt(index, 0).toString());
            cboMaNxb.setSelectedItem(tblBang.getValueAt(index, 1).toString());
            cboMaTl.setSelectedItem(tblBang.getValueAt(index, 2).toString());
            cboMaTg.setSelectedItem(tblBang.getValueAt(index, 3).toString());
            txtTenSach.setText(tblBang.getValueAt(index, 4).toString());
            txtNamXuatBan.setText(tblBang.getValueAt(index, 5).toString());
            txtSoLuong.setText(tblBang.getValueAt(index, 6).toString());
            txtDonGia.setText(tblBang.getValueAt(index, 7).toString());
            txtAnh.setText("");
            txtAnh.setIcon(new ImageIcon(newImage));

        }
    }

    SachDTO readFrom() {
        String maSach, maNxb, theLoai, maTg, tenSach, namXuatBan;
        int soLuong, giaMua;
        String anh;
        maSach = txtMaSach.getText().trim();
        maNxb = cboMaNxb.getSelectedItem().toString();
        theLoai = cboMaTl.getSelectedItem().toString();
        maTg = cboMaTg.getSelectedItem().toString();
        tenSach = txtTenSach.getText().trim();
        namXuatBan = txtNamXuatBan.getText().trim();
        soLuong = Integer.parseInt(txtSoLuong.getText().trim());
        giaMua = Integer.parseInt(txtDonGia.getText().trim());
        anh = txtAnh.getText().trim();
        return new SachDTO(maSach, maNxb, theLoai, maTg, tenSach, giaMua, soLuong, giaMua, anh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MainPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pInput = new javax.swing.JPanel();
        lbMaSach = new javax.swing.JLabel();
        lbMaNXB = new javax.swing.JLabel();
        lbMaTL = new javax.swing.JLabel();
        lbMaTG = new javax.swing.JLabel();
        lbTenSach = new javax.swing.JLabel();
        lbSoLuong = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        lnNamXuatBan = new javax.swing.JLabel();
        txtNamXuatBan = new javax.swing.JTextField();
        txtMaSach = new javax.swing.JTextField();
        cboMaNxb = new javax.swing.JComboBox<>();
        cboMaTl = new javax.swing.JComboBox<>();
        cboMaTg = new javax.swing.JComboBox<>();
        lbDonGia1 = new javax.swing.JLabel();
        pButton = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btChonAnh = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btHienThiTatCa = new javax.swing.JButton();
        pButton2 = new javax.swing.JPanel();
        btXuatExcel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtAnh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        btThongKe = new javax.swing.JButton();
        lbGiaMin2 = new javax.swing.JLabel();
        TongLoaiSoSach2 = new javax.swing.JLabel();
        txDonGiaMin = new javax.swing.JTextField();
        txTongSoLoaiSach2 = new javax.swing.JTextField();
        lbGiaMax = new javax.swing.JLabel();
        TongSoSach = new javax.swing.JLabel();
        txDonGiaMax = new javax.swing.JTextField();
        txTongSoSach = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbDonGia3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TkTenSach = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        MainPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÝ SÁCH");

        pInput.setBackground(new java.awt.Color(255, 255, 255));

        lbMaSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaSach.setText("MÃ SÁCH:");

        lbMaNXB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaNXB.setText("MÃ NXB:");

        lbMaTL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaTL.setText("MÃ THỂ LOẠI:");

        lbMaTG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaTG.setText("MÃ TÁC GIẢ:");

        lbTenSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenSach.setText("TÊN SÁCH:");

        lbSoLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSoLuong.setText("SỐ LƯỢNG:");

        txtTenSach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtDonGia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lnNamXuatBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnNamXuatBan.setText("NĂM XUẤT BẢN:");

        txtNamXuatBan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachActionPerformed(evt);
            }
        });

        lbDonGia1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDonGia1.setText("ĐƠN GIÁ:");

        javax.swing.GroupLayout pInputLayout = new javax.swing.GroupLayout(pInput);
        pInput.setLayout(pInputLayout);
        pInputLayout.setHorizontalGroup(
            pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTenSach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMaTG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pInputLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pInputLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(cboMaTg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMaNXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMaTL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboMaNxb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(cboMaTl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addComponent(lnNamXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pInputLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lbDonGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(253, Short.MAX_VALUE)))
        );
        pInputLayout.setVerticalGroup(
            pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInputLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMaNxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMaTl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaTG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMaTg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInputLayout.createSequentialGroup()
                    .addContainerGap(210, Short.MAX_VALUE)
                    .addComponent(lbDonGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );

        pButton.setBackground(new java.awt.Color(255, 255, 255));
        pButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btThem.setBackground(new java.awt.Color(153, 255, 204));
        btThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btThem.setText("Thêm");
        btThem.setToolTipText("");
        btThem.setBorder(null);
        btThem.setContentAreaFilled(false);
        btThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btThem.setPreferredSize(new java.awt.Dimension(200, 43));
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSua.setForeground(new java.awt.Color(255, 0, 0));
        btSua.setText("Sửa");
        btSua.setBorder(null);
        btSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSua.setPreferredSize(new java.awt.Dimension(57, 31));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btChonAnh.setBackground(new java.awt.Color(102, 102, 255));
        btChonAnh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btChonAnh.setForeground(new java.awt.Color(255, 255, 255));
        btChonAnh.setText("CHỌN ẢNH");
        btChonAnh.setBorder(null);
        btChonAnh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonAnhActionPerformed(evt);
            }
        });

        btXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btXoa.setForeground(new java.awt.Color(255, 0, 0));
        btXoa.setText("Xóa");
        btXoa.setBorder(null);
        btXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btXoa.setPreferredSize(new java.awt.Dimension(57, 31));
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btHienThiTatCa.setBackground(new java.awt.Color(0, 153, 0));
        btHienThiTatCa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btHienThiTatCa.setForeground(new java.awt.Color(255, 255, 255));
        btHienThiTatCa.setText("LÀM MỚI");
        btHienThiTatCa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHienThiTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHienThiTatCaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pButtonLayout = new javax.swing.GroupLayout(pButton);
        pButton.setLayout(pButtonLayout);
        pButtonLayout.setHorizontalGroup(
            pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(btSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(btXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btHienThiTatCa, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(btChonAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        pButtonLayout.setVerticalGroup(
            pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pButtonLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHienThiTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pButton2.setBackground(new java.awt.Color(255, 255, 255));
        pButton2.setForeground(new java.awt.Color(255, 255, 255));

        btXuatExcel.setBackground(new java.awt.Color(204, 255, 204));
        btXuatExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btXuatExcel.setText("XUẤT EXCEL");
        btXuatExcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        btXuatExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXuatExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pButton2Layout = new javax.swing.GroupLayout(pButton2);
        pButton2.setLayout(pButton2Layout);
        pButton2Layout.setHorizontalGroup(
            pButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pButton2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pButton2Layout.setVerticalGroup(
            pButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pButton2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(btXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtAnh.setBackground(new java.awt.Color(102, 255, 102));
        txtAnh.setForeground(new java.awt.Color(153, 153, 153));
        txtAnh.setToolTipText("");
        txtAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 153)));
        txtAnh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblBang.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 51), new java.awt.Color(102, 102, 102)));
        tblBang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ SÁCH", "MÃ NXB", "MÃ TL", "MÃ TG", "TÊN SÁCH", "NĂM XUẤT BẢN", "SỐ LƯỢNG", "ĐƠN GIÁ", "HÌNH ẢNH"
            }
        ));
        tblBang.setGridColor(new java.awt.Color(102, 102, 102));
        tblBang.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tblBang.setShowGrid(true);
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBang);

        btThongKe.setBackground(new java.awt.Color(153, 255, 153));
        btThongKe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_bar_chart_30px.png"))); // NOI18N
        btThongKe.setText("THỐNG KÊ");
        btThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongKeActionPerformed(evt);
            }
        });

        lbGiaMin2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGiaMin2.setText("ĐƠN GIÁ THẤP NHẤT:");

        TongLoaiSoSach2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TongLoaiSoSach2.setText("SỐ LOẠI SÁCH:");

        txDonGiaMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDonGiaMinActionPerformed(evt);
            }
        });

        txTongSoLoaiSach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTongSoLoaiSach2ActionPerformed(evt);
            }
        });

        lbGiaMax.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGiaMax.setText("ĐƠN GIÁ CAO NHẤT:");

        TongSoSach.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TongSoSach.setText("TỔNG SỐ SÁCH:");

        txDonGiaMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDonGiaMaxActionPerformed(evt);
            }
        });

        txTongSoSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTongSoSachActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 12), new java.awt.Color(255, 204, 0))); // NOI18N

        lbDonGia3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDonGia3.setText("TÊN SÁCH:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_25px_focus.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbDonGia3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(TkTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDonGia3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TkTenSach))
                        .addGap(75, 75, 75))))
        );

        javax.swing.GroupLayout MainPanel2Layout = new javax.swing.GroupLayout(MainPanel2);
        MainPanel2.setLayout(MainPanel2Layout);
        MainPanel2Layout.setHorizontalGroup(
            MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel2Layout.createSequentialGroup()
                .addGroup(MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanel2Layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanel2Layout.createSequentialGroup()
                                .addComponent(pInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)))))
                .addGap(0, 1208, Short.MAX_VALUE))
            .addGroup(MainPanel2Layout.createSequentialGroup()
                .addGroup(MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanel2Layout.createSequentialGroup()
                        .addGroup(MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanel2Layout.createSequentialGroup()
                                .addGap(333, 333, 333)
                                .addGroup(MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txTongSoLoaiSach2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txDonGiaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(MainPanel2Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addGroup(MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TongLoaiSoSach2)
                                    .addComponent(lbGiaMin2))
                                .addGap(224, 224, 224)
                                .addGroup(MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbGiaMax)
                                    .addComponent(TongSoSach))))
                        .addGap(18, 18, 18)
                        .addGroup(MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txDonGiaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txTongSoSach, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPanel2Layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(btThongKe)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanel2Layout.setVerticalGroup(
            MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGiaMin2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDonGiaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGiaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDonGiaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(MainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TongLoaiSoSach2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTongSoLoaiSach2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TongSoSach, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTongSoSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(MainPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMouseClicked
        int row = tblBang.getSelectedRow();
        showData(row);
    }//GEN-LAST:event_tblBangMouseClicked

    private void btXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXuatExcelActionPerformed
try {
            int choice = JOptionPane.showConfirmDialog(this, "Có chắc muốn lưu file?");
            if (choice == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Lưu thành công");
                ExcelExporter.exportToExcel(tblBang);
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Bạn chưa lưu");
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xuất Excel: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException ex) {

            JOptionPane.showMessageDialog(this, "Bạn đã hủy bỏ xuất Excel.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btXuatExcelActionPerformed

    private void btHienThiTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHienThiTatCaActionPerformed
        txtMaSach.setText("");
        cboMaNxb.setSelectedItem("NXB01");
        cboMaTl.setSelectedItem("TL01");
        cboMaTg.setSelectedItem("TG01");
        txtTenSach.setText("");
        txtNamXuatBan.setText("");
        txtSoLuong.setText("");
        txtDonGia.setText("");
        txtAnh.setText("");
        this.fillTable(qs.selectAll());
    }//GEN-LAST:event_btHienThiTatCaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int chon, index;
        String ma;
        index = tblBang.getSelectedRow();
        chon = JOptionPane.showConfirmDialog(this, "ban co muon xoa khong", "xoa du lieu", JOptionPane.YES_NO_CANCEL_OPTION, 3, null);
        if (chon == 0) {
            ma = tblBang.getValueAt(index, 0).toString();
            qs.delete(ma);
            JOptionPane.showMessageDialog(this, "xoa thanh cong");
            this.fillTable(qs.selectAll());
        } else {
            JOptionPane.showMessageDialog(this, "xoa that bai");
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonAnhActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & PNG imgs", "jpg", "png");
        fc.setFileFilter(filter);
        int result = fc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fc.getSelectedFile(); //Lấy URL hình
                this.i = ImageIO.read(file); // Lấy hình
                imgName = txtMaSach.getText().concat(".jpg"); //Tên hình
                // Thay đổi hình hiển thị
                txtAnh.setText("");
                txtAnh.setIcon(new ImageIcon(i.getScaledInstance(200, 230, Image.SCALE_DEFAULT)));
                revalidate();
                repaint();
            } catch (IOException ex) {
                Logger.getLogger(FromQlySach.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btChonAnhActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        index = tblBang.getSelectedRow();
        String ma = tblBang.getValueAt(index, 0).toString();
        ma = "%" + ma + "%";
        SachDTO s = this.readFrom();
        if (qs.upDatee(ma, s) > 0) {
            JOptionPane.showMessageDialog(this, "sua thanh cong");
            this.fillTable(qs.selectAll());
        } else {
            JOptionPane.showMessageDialog(this, "sua that bai");
        }

    }//GEN-LAST:event_btSuaActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        int chon;
        chon = JOptionPane.showConfirmDialog(this, "ban co muon them khong", "ghi du lieu",
                JOptionPane.YES_NO_CANCEL_OPTION, 3, null);
        if (chon == 0) {
            qs.insert(this.readFrom());
            JOptionPane.showMessageDialog(this, "them thanh cong");
            this.fillTable(qs.selectAll());
        } else {
            JOptionPane.showMessageDialog(this, "them that bai");
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachActionPerformed

    private void btThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongKeActionPerformed


    }//GEN-LAST:event_btThongKeActionPerformed

    private void txTongSoSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTongSoSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTongSoSachActionPerformed

    private void txDonGiaMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDonGiaMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDonGiaMinActionPerformed

    private void txTongSoLoaiSach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTongSoLoaiSach2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTongSoLoaiSach2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //  String ten = JOptionPane.showInputDialog("nhập tên cần tìm");
        String ten = TkTenSach.getText();
        if (qs.timkiem(ten).isEmpty()) {
            JOptionPane.showMessageDialog(this, "không tìm thấy tên");
            //this.fillTable(qs.getAll());
            return;
        }
        fillTable(qs.timkiem(ten));
        JOptionPane.showMessageDialog(this, "tìm thành công");

        
        
        
//    if(cboTK.getSelectedItem().equals("Tên Sách")){
//        String ten = TkTenSach.getText();
//        if (qs.timkiem(ten).isEmpty()) {
//            JOptionPane.showMessageDialog(this, "không tìm thấy tên");
//            //this.fillTable(qs.getAll());
//            return;
//        }
//        fillTable(qs.timkiem(ten));
//        JOptionPane.showMessageDialog(this, "tìm thành công");
//    }
    
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txDonGiaMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDonGiaMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDonGiaMaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromQlySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromQlySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromQlySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromQlySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromQlySach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel2;
    private javax.swing.JTextField TkTenSach;
    private javax.swing.JLabel TongLoaiSoSach2;
    private javax.swing.JLabel TongSoSach;
    private javax.swing.JButton btChonAnh;
    private javax.swing.JButton btHienThiTatCa;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThongKe;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btXuatExcel;
    private javax.swing.JComboBox<String> cboMaNxb;
    private javax.swing.JComboBox<String> cboMaTg;
    private javax.swing.JComboBox<String> cboMaTl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDonGia1;
    private javax.swing.JLabel lbDonGia3;
    private javax.swing.JLabel lbGiaMax;
    private javax.swing.JLabel lbGiaMin2;
    private javax.swing.JLabel lbMaNXB;
    private javax.swing.JLabel lbMaSach;
    private javax.swing.JLabel lbMaTG;
    private javax.swing.JLabel lbMaTL;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbTenSach;
    private javax.swing.JLabel lnNamXuatBan;
    private javax.swing.JPanel pButton;
    private javax.swing.JPanel pButton2;
    private javax.swing.JPanel pInput;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txDonGiaMax;
    private javax.swing.JTextField txDonGiaMin;
    private javax.swing.JTextField txTongSoLoaiSach2;
    private javax.swing.JTextField txTongSoSach;
    private javax.swing.JLabel txtAnh;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNamXuatBan;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
public class ExcelExporter {

        public static void exportToExcel(JTable table) throws IOException {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Chọn nơi lưu File");
            int userSelection = fileChooser.showSaveDialog(null);
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fileChooser.getSelectedFile();
                String filePath = fileToSave.getAbsolutePath();

                Workbook workbook = new XSSFWorkbook();
                Sheet sheet = workbook.createSheet("KhachHang");

                // Tạo tiêu đề
                Row headerRow = sheet.createRow(0);
                for (int i = 0; i < table.getColumnCount(); i++) {
                    headerRow.createCell(i).setCellValue(table.getColumnName(i));
                }

                // Thêm dữ liệu từ bảng vào tệp Excel
                for (int rowNum = 0; rowNum < table.getRowCount(); rowNum++) {
                    Row row = sheet.createRow(rowNum + 1);
                    for (int colNum = 0; colNum < table.getColumnCount(); colNum++) {
                        Object value = table.getValueAt(rowNum, colNum);
                        Cell cell = row.createCell(colNum);
                        if (value instanceof String) {
                            cell.setCellValue((String) value);
                        } else if (value instanceof Integer) {
                            cell.setCellValue((Integer) value);
                        } else if (value instanceof Date) {
                            // Xử lý dữ liệu ngày tháng
                            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                            cell.setCellValue(dateFormat.format((Date) value));
                        }
                        // Các kiểu dữ liệu khác có thể được xử lý tương tự
                    }
                }

                // Ghi dữ liệu vào tệp
                try (FileOutputStream outputStream = new FileOutputStream(filePath)) {
                    workbook.write(outputStream);

                }
            }
        }

    }
}
